profile:
  env: "dev"

app:
  name: "jotify"
  addr: "0.0.0.0:50501"
  group: "jotify"
  timeout: 1000 # millisecond
  read_weight: 1
  write_weight: 1

db:
  mysql:
    jotify_0:
      dsn: "jrmarcco:<passwd>@tcp(192.168.3.3:3306)/jotify_0?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=True&loc=Local&timeout=1s&readTimeout=3s&writeTimeout=3s&multiStatements=true&interpolateParams=true"
    jotify_1:
      dsn: "jrmarcco:<passwd>@tcp(192.168.3.3:3306)/jotify_1?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=True&loc=Local&timeout=1s&readTimeout=3s&writeTimeout=3s&multiStatements=true&interpolateParams=true"

etcd:
  username: "root"
  password: "<root_passwd>"
  endpoints:
    - "192.168.3.3:2379"

jwt:
  private: |
    -----BEGIN PRIVATE KEY-----
    MC4CAQAwBQYDK2VwBCIEINuchwbkYeYD/jnGLyPjRAufQGP+WUckh+PK6U4u7fk1
    -----END PRIVATE KEY-----
  public: |
    -----BEGIN PUBLIC KEY-----
    MCowBQYDK2VwAyEA818wiIDR2aqxvLKcyQL2qvVCYlSs2A/izQi/K109rlU=
    -----END PUBLIC KEY-----
